
openapi: 3.1.0
info:
  title: Ashtadhyayi Kosha Lookup
  version: "1.0"
servers:
  - url: https://YOUR-CLOUD-RUN-URL
paths:
  /lookup:
    get:
      summary: Search koshas for a headword
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
        - in: query
          name: sources
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, default: 25 }
      responses:
        "200":
          description: Results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    source: { type: string }
                    head: { type: string }
                    gloss: { type: string }
                    meta: { type: object }
  /healthz:
    get:
      summary: Health check
  /refresh:
    post:
      summary: Refresh kosha data
